### ISSUE TITLE
[BUG] Can’t load any data when the dashboard has set access password 

### ISSUE THREAD

**Issue by Muione** [hiDandelion/Nezha-Mobile#1]
My nezha dashboard has set an access password, the App can’t load my servers’ status data from the dashboard, and return an error: 
```
Connection timeout. Verify your server link and network connection.
```

**Comment by hiDandelion** [comment]
Thank you for your issue! This issue has been resolved in Version 1.2(11) by switching to API-based data fetching. You should be able to see the changes when the next release version is distributed.
