### ISSUE TITLE
流量显示

### ISSUE THREAD

**Issue by laoshi007** [hiDandelion/Nezha-Mobile#11]
想问一下是否可以在服务器列表中添加一个流量数据，要不然还要点进去才能看到具体流量使用情况。。。
还有在服务器详情页的时候，背景可以模糊显示壁纸吗

**Comment by hiDandelion** [comment]
你好，

Version 1.9(87)中已更改展示效果，这些更改已应用于测试版本，并将应用于下一次的发行版本。你可以在TestFlight中参与测试版的测试工作。
