### ISSUE TITLE
点击右上方的通过 IPv6 连接时，使用的仍然是 IPv4

### ISSUE THREAD

**Issue by cuteys** [hiDandelion/Nezha-Mobile#12]
点击右上方的通过 IPv6 连接时，使用的仍然是 IPv 连接；长按基本信息中的 IPv6 是正常的
![image](https://github.com/user-attachments/assets/5649002e-5c17-49fb-9ebe-c960d1996d07)

**Comment by hiDandelion** [comment]
已在Version 1.10(97)中修复。
