### ISSUE TITLE
ios18小组件不可用

### ISSUE THREAD

**Issue by Franklyingg** [hiDandelion/Nezha-Mobile#13]
app store直接下的，1.9最新版本iphone 12p
长按没有编辑选项
![IMG_0001](https://github.com/user-attachments/assets/885980ac-7993-49fd-86de-925ba1f4ce4e)

**Comment by hiDandelion** [comment]
尝试过删除小组件重新添加吗？

**Comment by Franklyingg** [comment]
尝试过，包括关机重启
另一个agent设备信息就有编辑选项

**Comment by Franklyingg** [comment]
重新下载安装已解决

不太稳定感觉，有时候会全白一小会，这阶段是在获取信息？

**Comment by hiDandelion** [comment]
在首次添加或更改设置后可能会有一段加载时间，如果后续刷新过程依旧出现就是不正常现象。

感谢你的反馈，我们将持续优化小组件的使用体验。
