### ISSUE TITLE
是否对哪吒v1版本进行支持

### ISSUE THREAD

**Issue by TTT-TD** [hiDandelion/Nezha-Mobile#15]
目前哪吒监控好像没看到后台有获取API Token的地方了

**Comment by hiDandelion** [comment]
支持哪吒面板v1的Nezha Mobile 1.12版本正在内测中。

请通过下面的链接加入Nezha Mobile 1.12版本的TestFlight Alpha测试群组。

[https://testflight.apple.com/join/6DP2JMXT](https://testflight.apple.com/join/6DP2JMXT)
