### ISSUE TITLE
使用时用户名和密码具体指的是什么?

### ISSUE THREAD

**Issue by lizhenmiao** [hiDandelion/Nezha-Mobile#16]
dashboard 链接可以使用 cdn 的 url 吗?
我的面板安装的是 v0.20.13 版本, 然后使用的是 github 认证登录, 这个我在手机端填写用户名和密码是 github 的用户名和密码吗? 望告知, 谢谢了!

**Comment by hiDandelion** [comment]
你好，

Nezha Mobile 现已不再支持 v0 版本 Dashboard。用户名密码登录方式仅适用于 v1 版本 Dashboard。Dashboard 链接可以使用启用了 CDN 的域名。
