### ISSUE TITLE
哪吒面板设置前端访问密码后，无法访问

### ISSUE THREAD

**Issue by okaysmart** [hiDandelion/Nezha-Mobile#2]
设置前端访问密码无法访问，去除访问密码则使用正常，希望能完善，谢谢

**Comment by hiDandelion** [comment]
Duplicate #1 
此问题已在Version 1.2(11)中解决。你可以通过 https://testflight.apple.com/join/C6vTc2dN 来测试更新版本。

**Comment by okaysmart** [comment]
看到之前的issue了，谢谢
