### ISSUE TITLE
按照官方教程设置后，报错"发生错误：接收数据时发生错误"

### ISSUE THREAD

**Issue by levywang** [hiDandelion/Nezha-Mobile#3]
Dashboard 版本：v0.18.6
Nezha Mobile APP 版本：v1.2

**Comment by hiDandelion** [comment]
你好，此错误的发生有三种情况：
1. 不正确的Dashboard链接
2. 未配置SSL或SSL证书无效
3. Dashboard版本过低

你的Dashboard版本受到兼容。因此请确认：
1. 没有使用协议头和末尾斜杠
2. HTTPS已配置且有效

**Comment by levywang** [comment]
主要原因是我没有配置 HTTPS，这个建议在官方文档中说明。

非常感谢！
