### ISSUE TITLE
关于Nezha_Mobile.GetServerDeatilError error 4 的连接的问题

### ISSUE THREAD

**Issue by Gm-aaa** [hiDandelion/Nezha-Mobile#5]
报错代码如题所示
- 域名正常、服务正常
- 关于DashBoard的链接，是否会因为CDN的原因导致连接失败？
- 尝试了直接ip:port也无法解决，对于套了CDN的域名。是否可以将服务不通过CDN，仅解析 到其他二级子域名解决？

**Comment by hiDandelion** [comment]
正常来说不会因为CDN问题导致错误，但如果由于CDN出现了机器人验证将会导致连接错误。解决方法：
1. 检查是否开启了Cloudflare的Attack Mode，如果可能请关闭
2. 如果必须使用Attack Mode，请在Rules配置规则放行/api路径。

**Comment by Gm-aaa** [comment]
感谢！
