### ISSUE TITLE
请问有无安卓版本的计划

### ISSUE THREAD

**Issue by zscontinent** [hiDandelion/Nezha-Mobile#6]
请问有无安卓版本的计划

**Comment by hiDandelion** [comment]
你好，

已有其他项目贡献者制作了Android版本的Nezha客户端。该issue将被关闭。

MDPings 是一个哪吒监控 Android 客户端，支持同时绑定多个哪吒监控面板，提供历史网络状态和延迟图表

项目地址：https://github.com/icylian/MDPings
