### ISSUE TITLE
iOS客户端显示所有的节点都是红色的离线状态

### ISSUE THREAD

**Issue by whereisxiaobaobei** [hiDandelion/Nezha-Mobile#8]
网页端显示的都是正常的,删除APP重新安装更换token也不行,这是什么问题呢?如果要收集相应的信息我这边可以配合,iOS版本 17.6.1,客户端版本1.7

**Comment by hiDandelion** [comment]
你好，

为了更好地确认问题，我需要了解更多信息。

请在服务器详情页面查看服务器的最后活跃时间，并确认它是否与你的现在时间差别超过1分钟？

**Comment by whereisxiaobaobei** [comment]
确实已经超过1分钟了,难道是我搭建nezha面板服务端的VPS时间设置的不对?

**Comment by hiDandelion** [comment]
是的，你应该调整 Dashboard 所在服务器的时间以使其与你的设备时间相符。
